"""Obfuscated embedding of the API token into the built exe.

`python keyvault.py` (run by build.bat) reads the token from the local .env / environment and
writes the git-ignored module `_embedded_key.py` holding it only in encrypted form.

This is obfuscation, not real secrecy: the decryption secret ships inside the exe too, so
anyone determined can recover the token. It only keeps the token out of plain strings and
out of git. Use a token that can be revoked and is limited to this endpoint.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import os
import sys
from pathlib import Path

_PEPPER = b"zugferd-studio/embedded-key/v1"
_OUT = Path(__file__).with_name("_embedded_key.py")


def _keystream(salt: bytes, length: int) -> bytes:
    out = b""
    counter = 0
    while len(out) < length:
        out += hashlib.sha256(_PEPPER + salt + counter.to_bytes(4, "big")).digest()
        counter += 1
    return out[:length]


def encrypt(token: str) -> str:
    data = token.encode("utf-8")
    salt = os.urandom(16)
    body = bytes(a ^ b for a, b in zip(data, _keystream(salt, len(data))))
    tag = hmac.new(_PEPPER, salt + body, hashlib.sha256).digest()[:8]
    return base64.b85encode(salt + tag + body).decode("ascii")


def decrypt(blob: str) -> str | None:
    try:
        raw = base64.b85decode(blob)
        salt, tag, body = raw[:16], raw[16:24], raw[24:]
        expected = hmac.new(_PEPPER, salt + body, hashlib.sha256).digest()[:8]
        if not hmac.compare_digest(tag, expected):
            return None
        data = bytes(a ^ b for a, b in zip(body, _keystream(salt, len(body))))
        return data.decode("utf-8")
    except Exception:  # noqa: BLE001 — a corrupt blob just means "no embedded key"
        return None


def embedded_token() -> str | None:
    """Return the token baked in at build time, if any."""
    try:
        from _embedded_key import BLOB  # type: ignore[import-not-found]
    except ImportError:
        return None
    return decrypt(BLOB)


def main() -> int:
    from ai_invoice_extractor import load_api_key

    token = load_api_key()
    if not token:
        print("Kein Token in Umgebung/.env gefunden - es wird nichts eingebettet.")
        _OUT.unlink(missing_ok=True)
        return 0
    _OUT.write_text(
        '"""Generated by keyvault.py - do not commit."""\n'
        f'BLOB = "{encrypt(token)}"\n',
        encoding="utf-8",
    )
    print("Token verschluesselt eingebettet (_embedded_key.py).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
